app/boat/urls.py
from django.urls import include, path

from . import views

app_name = 'boat'

apiurlpatterns = [
    path('create/', views.create, name='api_create'),
    path('update/<int:pk>/', views.update, name='api_update'),
    path('delete/<int:pk>/', views.delete, name='api_delete'),

    path('get_files/<int:pk>/', views.get_files, name='api_get_files'),
    path('calc_booking/<int:pk>/', views.calc_booking,
         name='api_calc_booking'),
    path('set_status/<int:pk>/', views.set_status, name='api_set_status'),
    path('get_models/<int:pk>/', views.get_models, name='api_get_models'),
    path('switch_fav/<int:pk>/', views.switch_fav, name='api_switch_fav')
]

urlpatterns = [
    path('my_boats/', views.my_boats, name='my_boats'),
    path('boats_on_moderation/', views.boats_on_moderation,
         name='boats_on_moderation'),
    path('favs/', views.favs, name='favs'),

    path('create/', views.create, name='create'),
    path('update/<int:pk>/', views.update, name='update'),
    path('booking/<int:pk>/', views.booking, name='booking'),
    path('view/<int:pk>/', views.view, name='view'),

    path('moderate/<int:pk>/', views.moderate, name='moderate'),
    path('accept/<int:pk>/', views.accept, name='accept'),
    path('reject/<int:pk>/', views.reject, name='reject'),
    path('search_boats/', views.search_boats, name='search_boats'),

    path('create_tariff/', views.create_tariff, name='create_tariff'),
    path('update_tariff/<int:pk>/', views.update_tariff, name='update_tariff'),
    path('delete_tariff/<int:pk>/', views.delete_tariff, name='delete_tariff'),

    path('terms/', views.terms, name='terms'),
    path('create_term/', views.create_term, name='create_term'),
    path('update_term/<int:pk>/', views.update_term, name='update_term'),
    path('delete_term/<int:pk>/', views.delete_term, name='delete_term'),

    path('api/', include(apiurlpatterns))
]

app/booking/urls.py
from django.urls import include, path

from . import views

app_name = 'booking'

apiurlpatterns = [
    path('set_status/<int:pk>/', views.set_status, name='api_set_status'),
    path('set_request_status/<int:pk>/',
         views.set_request_status, name="api_set_request_status")
]

urlpatterns = [
    path('my_bookings', views.my_bookings, name='my_bookings'),
    path('confirm/<int:boat_pk>/', views.confirm, name='confirm'),
    path('create/', views.create, name='create'),
    path('requests', views.requests, name='requests'),
    path('view/<int:pk>/', views.view, name='view'),
    path('all/', views.all, name='all'),
    path('api/', include(apiurlpatterns))
]

app/chat/urls.py
from django.urls import include, path

from . import views

app_name = 'chat'

apiurlpatterns = [
    path('send_message_booking/<int:pk>/', views.send_message_booking),
    path('get_new_messages_booking/<int:pk>/', views.get_new_messages_booking),

    path('get_new_messages_boat/<int:pk>/', views.get_new_messages_boat),
    path('send_message_boat/<int:pk>/', views.send_message_boat),

    path('get_new_messages/', views.get_new_messages),
    path('send_message/', views.send_message),

    path('get_new_support_messages/<int:user_pk>/',
         views.get_new_support_messages),
    path('send_support_message/<int:user_pk>/', views.send_support_message)
]

urlpatterns = [
    path('booking/<int:pk>/', views.booking, name='booking'),
    path('boat/<int:pk>/', views.boat, name='boat'),
    path('message/', views.message, name='message'),
    path('list/', views.list, name='list'),
    path('support/', views.support, name='support'),
    path('support_chat/<int:user_pk>/',
         views.support_chat, name='support_chat'),
    path('read_all/', views.read_all, name='read_all'),

    path('api/', include(apiurlpatterns))
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from boat import urls as boat_urls
from booking import urls as booking_urls
from chat import urls as chat_urls
from portal import urls as portal_urls
from telegram_bot import urls as telegram_bot_urls
from user import urls as user_urls

from . import views

urlpatterns = [
    path('', views.index),
    path(f'{settings.ADMIN_URL}/', admin.site.urls),

    path('user/', include(user_urls)),
    path('boats/', include(boat_urls)),
    path('bookings/', include(booking_urls)),
    path('telegram_bot/', include(telegram_bot_urls)),
    path('chat/', include(chat_urls)),
    path('portal/', include(portal_urls)),

    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/user/urls.py
from django.urls import include, path

from . import views

app_name = "user"

urlapipatterns = [
    path('update_avatar/', views.update_avatar, name='api_update_avatar'),
    path('send_verification_email/<email>/',
         views.send_verification_email, name="send_verification_email"),
    path('send_restore_password_email/', views.send_restore_password_email,
         name="send_restore_password_email"),
    path('generate_telegram_code/', views.generate_telegram_code,
         name='generate_telegram_code')
]

urlpatterns = [
     path('login/', views.login, name='login'),
     path('logout/', views.logout, name='logout'),
     path('register/', views.register, name='register'),
     path('update/', views.update, name='update'),
     path('restore_password/', views.restore_password,
          name='restore_password'),

     path('verify/<token>/', views.verify, name='verify'),
     path('change_password/<token>/', views.change_password,
          name='change_password'),
     path('support/', views.support, name='support'),
     path('api/', include(urlapipatterns))
]

app/user/forms.py
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from django.forms import BooleanField, ModelForm, PasswordInput
from django.utils.translation import ugettext_lazy as _

from boat.models import Boat

from .models import User


class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password']
        labels = {
            'email': _('Эл. почта'),
            'password': 'Пароль'
        }
        widgets = {
            'password': PasswordInput
        }


class UpdateForm(ModelForm):
    is_boat_owner = BooleanField(label="Являюсь арендодателем",
                                 required=False)

    def clean_is_boat_owner(self):
        is_boat_owner = self.cleaned_data.get('is_boat_owner')
        if not is_boat_owner:
            if self.instance.boats.exclude(status=Boat.Status.DELETED) \
                                  .exists():
                raise ValidationError(
                    '- Для того чтобы перестать быть арендодателем, ' +
                    'необходимо удалить свой флот')
        return is_boat_owner

    def save(self, commit=True):
        m = super(UpdateForm, self).save(commit=False)

        boat_owner_group, _ = Group.objects.get_or_create(name='boat_owner')
        if self.cleaned_data.get('is_boat_owner', False):
            self.instance.groups.add(boat_owner_group)
        else:
            self.instance.groups.remove(boat_owner_group)

        if commit:
            m.save()
        return m

    class Meta:
        model = User
        fields = ('first_name', 'email_notification',
                  'is_boat_owner', 'use_dark_theme')

app/user/views.py
import logging
import random

import jwt
import requests
from django.conf import settings
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import redirect, render

from config import tokens
from config.exceptions import InvalidToken
from emails.exceptions import EmailLagError
from emails.models import UserEmail
from notification import utils as notify
from user.forms import UpdateForm

from .models import TelegramUser, User

logger_admin_mails = logging.getLogger('mail_admins')
logger = logging.getLogger(__name__)

BOAT_OWNER_GROUP = 'boat_owner'


@permission_required('user.view_support', raise_exception=True)
def support(request):
    return render(request, 'user/support.html',
                  context={'admin_url': settings.ADMIN_URL})


def get_bool(value):
    if value in (True, 'True', 'true', '1', 'on'):
        return True
    return False


def check_recaptcha(request):  # pragma: no cover
    recaptcha = request.POST.get('g-recaptcha-response')
    if recaptcha:
        resp = requests.post(
            'https://www.google.com/recaptcha/api/siteverify',
            data={'secret': settings.RECAPTCHA_SERVERSIDE_KEY,
                  'response': recaptcha})
        return resp.json()['success']
    return False


def get_tgcode_message(code):
    return f'Ваш код для авторизации в Телеграм боте: ' \
           f'<strong>{code}</strong>. Отправьте боту команду ' \
           f'<span class="text-primary">/auth</span> и следуйте инструкциям.'


def verify(request, token):
    User = get_user_model()
    try:
        payload = tokens.check_token(token, tokens.VERIFICATION)
        user = User.objects.get(pk=payload.get('user_id'))
        if not user.email_confirmed:
            user.email_confirmed = True
            user.save()
            django_login(request, user)
            notify.send_greetings_to_user(user)
        return render(request, 'user/verified.html')
    except (TypeError, ValueError, OverflowError, User.DoesNotExist,
            InvalidToken, jwt.InvalidSignatureError,
            jwt.exceptions.DecodeError):
        msg = 'Неверная ссылка'
    except jwt.ExpiredSignatureError:
        msg = 'Ссылка устарела'

    return render(request, 'user/invalid_link.html', context={'msg': msg},
                  status=400)


def send_verification_email(request, email):
    try:
        user = User.objects.get(email=email)
        if not user.email_confirmed:
            UserEmail.send_verification_email(request, user)
    except (User.DoesNotExist, EmailLagError):
        pass
    return JsonResponse({})


@login_required
def update_avatar(request):
    avatar = request.FILES.get('avatar')
    user = request.user
    user.avatar = avatar
    user.avatar_sm = avatar
    user.save()

    return JsonResponse({
        'avatar': user.avatar.url,
        'avatar_sm': user.avatar_sm.url
    })


@login_required
def update(request):
    def _get_tgcode_message():
        if (hasattr(request.user, 'telegramuser') and
                not request.user.telegramuser.chat_id):
            return get_tgcode_message(
                request.user.telegramuser.verification_code)
        return ''

    if request.method == 'GET':
        initial = {
            'is_boat_owner': request.user.groups
                                         .filter(name=BOAT_OWNER_GROUP)
                                         .exists()
        }
        form = UpdateForm(instance=request.user, initial=initial)
        return render(request, 'user/update.html',
                      context={'form': form,
                               'tgcode_message': _get_tgcode_message()})

    elif request.method == 'POST':
        user = request.user
        form = UpdateForm(request.POST, instance=user)

        if form.is_valid():
            form.save()
            return render(request, 'user/update.html',
                          context={'form': form,
                                   'success': 'Профиль сохранен.'})

        return render(request, 'user/update.html',
                      context={'form': form,
                               'tgcode_message': _get_tgcode_message()},
                      status=400)


def login(request):
    if request.method == 'GET':
        return render(
            request, 'user/login.html',
            context={'recaptcha_key': settings.RECAPTCHA_CLIENTSIDE_KEY})

    elif request.method == 'POST':
        data = request.POST

        if not settings.DEBUG:  # pragma: no cover
            if not check_recaptcha(request):
                context = {
                    'recaptcha_key': settings.RECAPTCHA_CLIENTSIDE_KEY,
                    'errors': 'Проверка "Я не робот" не пройдена',
                    'email': data['email']
                }
                return render(request, 'user/login.html', context=context)

        email_lower = data['email'].lower()
        user = authenticate(request, email=email_lower,
                            password=data['password'])
        if user is not None:
            if user.email_confirmed:
                django_login(request, user)
                return redirect(request.POST.get('next') or '/')

            try:
                UserEmail.send_verification_email(request, user)
            except Exception as e:  # pragma: no cover
                logger.error(str(e))

            context = {
                'title': 'Подтвердите почтовый адрес',
                'content': 'Чтобы пользоваться сервисом, вам необходимо \
                           подтвердить свой почтовый адрес.\nПисьмо с \
                           активацией отправлено на почту %s.' % user.email
            }
            return render(request, 'user/email_sent.html',
                          context=context, status=400)

        context = {
            'recaptcha_key': settings.RECAPTCHA_CLIENTSIDE_KEY,
            'errors': 'Неверный логин и/или пароль',
            'email': data['email']
        }
        return render(request, 'user/login.html', context=context, status=400)


@login_required
def logout(request):
    django_logout(request)
    return redirect('/')


def restore_password(request):
    return render(
        request,
        'user/restore_password.html',
        context={'recaptcha_key': settings.RECAPTCHA_CLIENTSIDE_KEY})


@login_required
def generate_telegram_code(request):
    def _gen_code():
        code = str(random.randint(1, 999999))
        code = '0' * 5 + code
        code = code[-6:]
        return code

    code = _gen_code()
    while TelegramUser.objects \
                      .filter(chat_id__isnull=True, verification_code=code) \
                      .exists():
        code = _gen_code()  # pragma: no cover

    TelegramUser.objects.filter(user=request.user).delete()
    TelegramUser.objects.create(user=request.user, verification_code=code)
    return JsonResponse({
        'verification_code': code,
        'message': get_tgcode_message(code)
    })


def change_password(request, token):
    User = get_user_model()
    try:
        payload = tokens.check_token(token, tokens.RESTORE_PASSWORD)
        user = User.objects.get(pk=payload.get('user_id'))
        if request.method == 'GET':
            return render(request, 'user/change_password.html',
                          context={'email': user.email, 'token': token})
        elif request.method == "POST":
            if not user.email_confirmed:
                user.email_confirmed = True
            user.set_password(request.POST['password1'])
            user.save()
            django_login(request, user)
            return redirect('/')
    except (TypeError, ValueError, OverflowError, User.DoesNotExist,
            InvalidToken, jwt.InvalidSignatureError,
            jwt.exceptions.DecodeError):
        msg = 'Неверная ссылка'
    except jwt.ExpiredSignatureError:
        msg = 'Ссылка устарела'

    return render(request, 'user/invalid_link.html',
                  context={'msg': msg}, status=400)


def send_restore_password_email(request):
    if not settings.DEBUG:  # pragma: no cover
        if not check_recaptcha(request):
            return render(
                request, 'user/restore_password.html',
                context={'recaptcha_key': settings.RECAPTCHA_CLIENTSIDE_KEY,
                         'errors': 'Проверка "Я не робот" не пройдена'})

    try:
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        UserEmail.send_restore_password_email(request, user)
    except (User.DoesNotExist, EmailLagError):
        pass

    context = {
        'title': 'Восстановление пароля',
        'content': 'Письмо для сброса пароля отправлено на почту %s' % email
    }

    return render(request, 'user/email_sent.html', context=context)


def register(request):

    def render_error(msg):
        context = {
            'errors': msg,
            'first_name': data.get('first_name'),
            'recaptcha_key': settings.RECAPTCHA_CLIENTSIDE_KEY
        }
        return render(request, 'user/register.html',
                      context=context, status=400)

    if request.method == 'GET':
        return render(
            request, 'user/register.html',
            context={'recaptcha_key': settings.RECAPTCHA_CLIENTSIDE_KEY})

    elif request.method == "POST":
        data = request.POST

        if not settings.DEBUG:  # pragma: no cover
            if not check_recaptcha(request):
                return render_error('Проверка "Я не робот" не пройдена')

        email_lower = data['email'].lower()

        if User.objects.filter(email=email_lower).exists():
            return render_error(

app/user/templates/user/change_password.html
{% extends 'user/main.html' %}

{% load static %}

{% block title %}Смена пароля{% endblock %}
{% block content %}
    <script type="text/javascript" src="{% static 'user/js/change_password.min.js' %}"></script>

    <div class="container-lg mw-lg-500">
        <div class="card p-3">

            <form action="{% url 'user:change_password' token=token %}" method="post" class="needs-validation" novalidate>
                {% csrf_token %}

                <h1 class="h3 mb-3 font-weight-normal text-center">Смена пароля</h1>    

                {% if errors %}
                    <div class="alert alert-danger">{{ errors }}</div>
                {% endif %}
                
                <div class="form-floating mb-3">           
                    <input id="email" type="email" name="email" placeholder="Эл. почта" required class="form-control" autocomplete="username" value="{{ email }}" readonly>
                    <label for="email">Эл. почта</label>
                </div>

                <div class="form-floating mb-3">                   
                    <input id="password1Input" type="password" name="password1" placeholder="Пароль" required class="form-control" autocomplete="new-password">
                    <label for="password1Input">Пароль</label>
                    <div class="invalid-tooltip">Введите пароль</div>
                </div>
                <div class="form-floating mb-3">          
                    <input id="password2Input" type="password" name="password2" placeholder="Повторите пароль" required class="form-control" autocomplete="new-password">
                    <label for="password2Input">Повторите пароль</label>
                    <div class="invalid-tooltip">Повторите пароль</div>
                </div>

                <button class="btn btn-lg btn-primary w-100" type="submit">Сменить пароль</button>
            </form>
        </div>
    </div>
{% endblock %}

app/user/templates/user/email_sent.html
{% extends 'user/main.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="container-lg mw-lg-500">
        <div class="card p-3 text-center">
            {% if header %}
                <h3>{{ header }}</h3>
            {% endif %}
            <div class="verification-email">{{ content|linebreaks }}</div>
            <a href="/">Вернуться на главную страницу</a>
        </div>
    </div>   
{% endblock %}

app/user/templates/user/login.html
{% extends 'user/main.html' %}

{% load static %}
{% load extras %}

{% block title %}Авторизация{% endblock %}

{% block content %}
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

    <div class="container-lg mw-lg-500">
        <div class="card p-3">
            <form id="signin" action="{% url 'user:login' %}?next={{ request.GET.next|urlencode }}" method="post" class='needs-validation' novalidate>
                {% csrf_token %}

                <h1 class="h3 mb-3 font-weight-normal text-center">Авторизация</h1>  
                
                {% if errors %}
                    <div class="alert alert-danger">{{ errors }}</div>
                {% endif %}
                
                <div class="form-floating mb-3">            
                    <input id="email" type="email" name="email" {% if email %}value={{ email }} {% endif %} autocomplete="username email" placeholder="Эл. почта" required class="form-control" >
                    <label for="email">Эл. почта</label>
                    <div class="invalid-tooltip">Введите эл. почту</div>
                </div>

                <div class="form-floating mb-3">
                    <input id="password" type="password" name="password" autocomplete="current-password" placeholder="Пароль" required class="form-control" {% if errors %} autofocus {% endif %}>
                    <label for="password">Пароль</label>
                    <div class="invalid-tooltip">Введите пароль</div>
                </div>

                <input type="hidden" name="next" value={{ request.GET.next }} >

                {% is_debug as is_debug %}
                {% if not is_debug %}
                    <div class="g-recaptcha mb-3" data-sitekey="{{ recaptcha_key }}" data-callback="recaptchaCallback"></div>
                {% endif %}
                
                <button class="btn btn-lg btn-primary w-100 mb-3" type="submit" {% if not is_debug %}disabled{% endif %}>Войти</button>
                
                <div class="mb-2 text-center">
                    <div class="mb-2"><a href="{% url 'user:restore_password' %}">Восстановить пароль</a></div>
                    <div><a href="{% url 'user:register' %}">Зарегистрироваться</a></div>
                </div>
            </form>
        </div>
    </div>
    
{% endblock %}

app/user/templates/user/support.html
{% extends 'main.html' %}

{% block title %}Поддержка{% endblock  %}

{% block content %}
    <div class="container-md">
        <section class="jumbotron text-center">
            <h1 class="jumbotron-heading">Поддержка</h1>   
        </section>
        
        <div class="mb-3">
            <div class="row row-cols-1 row-cols-xl-2 g-3">
                {% if user.is_staff %}
                    <div class="col">
                        <div class="card box-shadow">
                            <div class="row g-0">
                                <div class="col-2 text-center align-self-center p-3">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16">
                                        <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
                                        <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
                                    </svg>
                                </div>
                                
                                <div class="col-10">
                                    <div class="card-body">
                                        <h5 class="card-title"><a href="/{{ admin_url }}/" class="stretched-link">Админка</a></h5>
                                        <p class="card-text">Управление сайтом</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}

                {% if perms.boat.view_boats_on_moderation %}
                    <div class="col">
                        <div class="card box-shadow">
                            <div class="row g-0">
                                <div class="col-2 text-center align-self-center p-3">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-check2-square" viewBox="0 0 16 16">
                                        <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z"/>
                                        <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z"/>
                                    </svg>
                                </div>
                                
                                <div class="col-10">
                                    <div class="card-body">
                                        <h5 class="card-title"><a href="{% url 'boat:boats_on_moderation' %}" class="stretched-link">Модерация</a></h5>
                                        <p class="card-text">Лодки, которые необходимо одобрить к публикации</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}

                {% if perms.user.support_chat %}
                    <div class="col">
                        <div class="card box-shadow">
                                <div class="row g-0">
                                    <div class="col-2 text-center align-self-center p-3">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-chat-right-text mw-100" viewBox="0 0 16 16">
                                            <path d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
                                            <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                                        </svg>
                                    </div>
                                
                                    <div class="col-10">
                                        <div class="card-body">
                                            <h5 class="card-title"><a href="{% url 'chat:support' %}" class="stretched-link">Поддержка</a></h5>
                                            <p class="card-text">Чат с пользователем</p>     
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                {% endif %}

                {% if perms.user.view_all_bookings %}
                    <div class="col">
                        <div class="card box-shadow">
                            <div class="row g-0">
                                <div class="col-2 text-center align-self-center p-3">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-calendar3" viewBox="0 0 16 16">
                                        <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
                                        <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                                    </svg>
                                </div>
                                
                                <div class="col-10">
                                    <div class="card-body">
                                        <h5 class="card-title"><a href="{% url 'booking:all' %}" class="stretched-link">Бронирования</a></h5>
                                        <p class="card-text">Список всех бронирований</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock  %}