app/boat/urls.py
from django.urls import include, path

from . import views

app_name = 'boat'

apiurlpatterns = [
    path('create/', views.create, name='api_create'),
    path('update/<int:pk>/', views.update, name='api_update'),
    path('delete/<int:pk>/', views.delete, name='api_delete'),

    path('get_files/<int:pk>/', views.get_files, name='api_get_files'),
    path('calc_booking/<int:pk>/', views.calc_booking,
         name='api_calc_booking'),
    path('set_status/<int:pk>/', views.set_status, name='api_set_status'),
    path('get_models/<int:pk>/', views.get_models, name='api_get_models'),
    path('switch_fav/<int:pk>/', views.switch_fav, name='api_switch_fav')
]

urlpatterns = [
    path('my_boats/', views.my_boats, name='my_boats'),
    path('boats_on_moderation/', views.boats_on_moderation,
         name='boats_on_moderation'),
    path('favs/', views.favs, name='favs'),

    path('create/', views.create, name='create'),
    path('update/<int:pk>/', views.update, name='update'),
    path('booking/<int:pk>/', views.booking, name='booking'),
    path('view/<int:pk>/', views.view, name='view'),

    path('moderate/<int:pk>/', views.moderate, name='moderate'),
    path('accept/<int:pk>/', views.accept, name='accept'),
    path('reject/<int:pk>/', views.reject, name='reject'),
    path('search_boats/', views.search_boats, name='search_boats'),

    path('create_tariff/', views.create_tariff, name='create_tariff'),
    path('update_tariff/<int:pk>/', views.update_tariff, name='update_tariff'),
    path('delete_tariff/<int:pk>/', views.delete_tariff, name='delete_tariff'),

    path('terms/', views.terms, name='terms'),
    path('create_term/', views.create_term, name='create_term'),
    path('update_term/<int:pk>/', views.update_term, name='update_term'),
    path('delete_term/<int:pk>/', views.delete_term, name='delete_term'),

    path('api/', include(apiurlpatterns))
]

app/booking/urls.py
from django.urls import include, path

from . import views

app_name = 'booking'

apiurlpatterns = [
    path('set_status/<int:pk>/', views.set_status, name='api_set_status'),
    path('set_request_status/<int:pk>/',
         views.set_request_status, name="api_set_request_status")
]

urlpatterns = [
    path('my_bookings', views.my_bookings, name='my_bookings'),
    path('confirm/<int:boat_pk>/', views.confirm, name='confirm'),
    path('create/', views.create, name='create'),
    path('requests', views.requests, name='requests'),
    path('view/<int:pk>/', views.view, name='view'),
    path('all/', views.all, name='all'),
    path('api/', include(apiurlpatterns))
]

app/chat/urls.py
from django.urls import include, path

from . import views

app_name = 'chat'

apiurlpatterns = [
    path('send_message_booking/<int:pk>/', views.send_message_booking),
    path('get_new_messages_booking/<int:pk>/', views.get_new_messages_booking),

    path('get_new_messages_boat/<int:pk>/', views.get_new_messages_boat),
    path('send_message_boat/<int:pk>/', views.send_message_boat),

    path('get_new_messages/', views.get_new_messages),
    path('send_message/', views.send_message),

    path('get_new_support_messages/<int:user_pk>/',
         views.get_new_support_messages),
    path('send_support_message/<int:user_pk>/', views.send_support_message)
]

urlpatterns = [
    path('booking/<int:pk>/', views.booking, name='booking'),
    path('boat/<int:pk>/', views.boat, name='boat'),
    path('message/', views.message, name='message'),
    path('list/', views.list, name='list'),
    path('support/', views.support, name='support'),
    path('support_chat/<int:user_pk>/',
         views.support_chat, name='support_chat'),
    path('read_all/', views.read_all, name='read_all'),

    path('api/', include(apiurlpatterns))
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from boat import urls as boat_urls
from booking import urls as booking_urls
from chat import urls as chat_urls
from portal import urls as portal_urls
from telegram_bot import urls as telegram_bot_urls
from user import urls as user_urls

from . import views

urlpatterns = [
    path('', views.index),
    path(f'{settings.ADMIN_URL}/', admin.site.urls),

    path('user/', include(user_urls)),
    path('boats/', include(boat_urls)),
    path('bookings/', include(booking_urls)),
    path('telegram_bot/', include(telegram_bot_urls)),
    path('chat/', include(chat_urls)),
    path('portal/', include(portal_urls)),

    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/booking/models.py
import datetime

from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from boat.models import Base, Boat, Model
from user.models import User

from .exceptions import (BookingDateRangeException,
                         BookingDuplicatePendingException)


class BookingQuerySet(models.QuerySet):
    """QuerySet бронирования."""
    def in_range(self, start_date: datetime.date, end_date: datetime.date):
        """Отфильтровать за период.

        Args:
            start_date: дата начала
            end_date: дата окончания

        """
        return self.filter(
            Q(start_date__range=(start_date, end_date)) |
            Q(end_date__range=(start_date, end_date)) |
            Q(start_date__lt=start_date, end_date__gt=end_date)
        )

    def blocked_in_range(self,
                         start_date: datetime.date, end_date: datetime.date):
        """Отфильтровать заблокированные бронирования за период.

        Args:
            start_date: дата начала
            end_date: дата окончания

        """
        return self.filter(status__in=Booking.BLOCKED_STATUSES) \
                   .in_range(start_date, end_date)

    def filter_by_status(self, status: str):
        """Отфильтровать бронирования по статусу.

        Args:
            status: статус

        """
        mapping = {
            'pending': Booking.PENDING_STATUSES,
            'active': Booking.ACTIVE_STATUSES,
            'done': Booking.DONE_STATUSES,
        }
        statuses = mapping.get(status)
        if not statuses:
            return self
        return self.filter(status__in=statuses)


class Booking(models.Model):
    """Модель бронирования."""

    class Status(models.IntegerChoices):
        """Статусы бронирования."""
        PENDING = 0, _("Ожидание подтверждения")
        DECLINED = -1, _("Отменено")
        ACCEPTED = 1, _("Подтверждено")
        PREPAYMENT_REQUIRED = 2, _("Ожидание предоплаты")
        ACTIVE = 3, _("Активно")
        DONE = 4, _("Завершено")

    BLOCKED_STATUSES = [Status.ACCEPTED,
                        Status.PREPAYMENT_REQUIRED,
                        Status.ACTIVE,
                        Status.DONE]

    PENDING_STATUSES = [Status.PENDING, ]
    ACTIVE_STATUSES = [Status.ACCEPTED,
                       Status.PREPAYMENT_REQUIRED,
                       Status.ACTIVE]

    DONE_STATUSES = [Status.DONE, Status.DECLINED]

    STATUSES_CAN_BE_DECLINED = [Status.PENDING, Status.PREPAYMENT_REQUIRED]

    boat = models.ForeignKey(
        Boat, on_delete=models.PROTECT, related_name='bookings')
    renter = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='bookings')
    status = models.IntegerField(
        choices=Status.choices, default=Status.PENDING)

    start_date = models.DateField()
    end_date = models.DateField()
    total_sum = models.DecimalField(max_digits=8, decimal_places=2)
    spec = models.JSONField(null=True, blank=True)

    objects = models.Manager.from_queryset(BookingQuerySet)()

    def clean(self):
        if self.pk is None:
            accepted_bookings_exist = \
                Booking.objects \
                       .filter(boat=self.boat) \
                       .blocked_in_range(self.start_date, self.end_date) \
                       .exists()

            if accepted_bookings_exist:
                raise BookingDateRangeException()

            duplicate_bookings_exist = Booking.objects.filter(
                boat=self.boat,
                renter=self.renter,
                status=self.Status.PENDING
            ).in_range(self.start_date, self.end_date).exists()

            if duplicate_bookings_exist:
                raise BookingDuplicatePendingException()

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Booking, self).save(*args, **kwargs)

    def __str__(self):
        return f'Бронь № {self.pk} - {self.boat}'


class Prepayment(models.Model):
    """Модель предоплаты."""
    booking = models.OneToOneField(
        Booking, primary_key=True, on_delete=models.CASCADE)
    until = models.DateTimeField()


class BoatInfo(models.Model):
    """Модель информации о лодке."""
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE,
                                   primary_key=True, related_name="boat_info")
    prepayment_required = models.BooleanField()
    term_content = models.TextField(null=True, blank=True)

    owner = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="requests")
    model = models.ForeignKey(
        Model, on_delete=models.PROTECT, related_name="bookings")
    type = models.IntegerField(choices=Boat.Type.choices)
    base = models.ForeignKey(Base, on_delete=models.PROTECT,
                             related_name="bookings", null=True, blank=True)
    photo = models.ImageField()
    spec = models.JSONField(null=True, blank=True)


class BoatInfoCoordinates(models.Model):
    """Модель информации о координатах лодки."""
    boat_info = models.OneToOneField(BoatInfo, on_delete=models.CASCADE,
                                     primary_key=True,
                                     related_name="coordinates")
    lon = models.DecimalField(max_digits=9, decimal_places=6)
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    address = models.TextField()
    state = models.CharField(max_length=255, db_index=True)

app/booking/templates/booking/all.html
{% extends 'main.html' %}

{% load static %}
{% load booking_extras %}

{% block title %}Все бронирования{% endblock  %}

{% block content %}   
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Все бронирования</h1>
        </div>
    </section>

    {% include 'booking/nav_status.html' %}

    {% if bookings %}
        <div class="album mb-3">
            <div class="container">
                <div class="row row-cols-1 row-cols-xl-2 g-3">
                    {% for booking in bookings %}
                        <div class="col">
                            <div class="card box-shadow">
                                <div class="row g-0">
                                    <div class="col-md-4">
                                        <a href="{% url 'booking:view' booking.id %}" >
                                            {% include 'booking/boat_carousel.html'%}
                                        </a>
                                    </div>
                                    
                                    <div class="col-md-8">
                                        <div class="card-body d-flex flex-column">
                                            {% include 'booking/boat_card.html' %}
                                            <div class="alert {{ booking.status|get_status_color }} p-2 mb-2" role="alert">
                                                {% include 'booking/booking_data.html' %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <div class="text-center text-muted">Нет бронирований</div>
    {% endif %}

{% endblock  %}

app/booking/templates/booking/boat_card.html
{% load booking_extras %}
<h5 class="card-title mb-2 ">
    {% with booking.boat_info.spec|boatspectoobj as spec %}
        {{ booking.boat_info.model.manufacturer.name }} {{ booking.boat_info.model.name }} "{{ spec.name }}"
    {% endwith %}
</h5>     
<h6 class="card-subtitle mb-3 text-muted">{{ booking.boat_info.get_type_display }}</h6>

app/booking/templates/booking/boat_carousel.html
{% if booking.boat_info.photo %}

    <div class="position-relative">
        <img src="{{ booking.boat_info.photo.url }}" class="card-img" />
        <a type="button" class="carousel-control-full-screen" data-bs-toggle='modal' data-bs-target="#fullscreenViewer{{ booking.pk }}" title="Во весь экран">
            <span class="carousel-control-full-screen-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Full screen</span>
        </a>
    </div>

{% else %}

    <div class="card-img"></div>

{% endif %}

{% with booking.pk|stringformat:'s' as booking_pk_str %}
    {% include 'boat/fullscreen_viewer.html' with fullscreen_viewer_id='fullscreenViewer'|add:booking_pk_str photo=booking.boat_info.photo %}
{% endwith %}

app/booking/templates/booking/boat_location.html
{% load static %}
{% load extras %}

<div>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#0d6efd" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
    </svg>
    {% if booking.boat_info.base %}
        <a href="#" data-bs-toggle="modal" data-bs-target="#modalMap" class="text-primary"
            data-coordinates-lat="{{ booking.boat_info.base.lat|stringformat:".6f" }}"
            data-coordinates-lon="{{ booking.boat_info.base.lon|stringformat:".6f" }}"
            data-coordinates-address="{{ booking.boat_info.base.address }}">{{ booking.boat_info.base.name }}, {{ booking.boat_info.base.state }}</a>
    {% elif booking.boat_info|hasattr:'coordinates' %}
        <a href="#" data-bs-toggle="modal" data-bs-target="#modalMap" class="text-primary"
            data-coordinates-lat="{{ booking.boat_info.coordinates.lat|stringformat:".6f" }}"
            data-coordinates-lon="{{ booking.boat_info.coordinates.lon|stringformat:".6f" }}"
            data-coordinates-address="{{ booking.boat_info.coordinates.address }}">{{ booking.boat_info.coordinates.state }}</a>
    {% else %}
        <span class="text-muted">Местоположение не указано</span>
    {% endif %}
</div>

app/booking/templates/booking/booking_data.html
<div>
    <h5>{{ booking.get_status_display }}</h5>
    <div>Бронирование № {{ booking.pk }}</div>
    <div>{{ booking.start_date|date:'d b. Y' }} - {{ booking.end_date|date:'d b. Y' }}</div>
    <div><strong>{{ booking.total_sum }}&nbsp;₽</strong></div>
    {% if booking.renter != user %}
        <div class="mt-2">
            {% if booking.renter.avatar %}
                <img height="32" width="32" src="{{ booking.renter.avatar.url }}" class="of-cover rounded-circle bg-light">
            {% endif %}
            <span class="text-muted align-middle">{{ booking.renter.first_name }}</span>
        </div>
    {% endif %}
</div>

app/booking/templates/booking/bookings_list_card.html
{% load booking_extras %}

<div class="album mb-3">
    <div class="container">
        <div class="row row-cols-1 row-cols-xl-2 g-3">
            {% for booking in bookings %}
                <div class="col">
                    <div class="card box-shadow">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <a href="{% url 'booking:view' booking.id %}" >
                                    {% include 'booking/boat_carousel.html' %}
                                </a>    
                            </div>
                            
                            <div class="col-md-8">
                                <div class="card-body d-flex flex-column">
                                    {% include 'booking/boat_card.html' %}
                                    <div class="alert {{ booking.status|get_status_color }} p-2 mb-2" role="alert">
                                        {% include 'booking/booking_data.html' %}
                                    </div>
                                    <div class="dropdown mt-auto">
                                        <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuStatus{{ booking.pk }}" data-bs-toggle="dropdown" aria-expanded="false">
                                            Действия
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuStatus{{ booking.pk }}">
                                            {% if booking.status == Status.PENDING %}
                                                <li>
                                                    <a class="dropdown-item text-danger" href="#" data-booking-id="{{ booking.pk }}" data-status="{{ Status.DECLINED }}">
                                                        Отменить бронь
                                                    </a>
                                                </li>
                                            {% endif %}      
                                            <li><a class="dropdown-item" href="{% url 'chat:booking' booking.pk %}?back={{ request.get_full_path }}">Чат</a></li>                           
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

app/booking/templates/booking/my_bookings.html
{% extends 'main.html' %}

{% load static %}

{% block title %}Мои бронирования{% endblock  %}

{% block content %}
    <script type="text/javascript" src="{% static 'booking/js/my_bookings.min.js' %}"></script>
    
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Мои бронирования</h1>
        </div>
    </section>

    {% include 'booking/nav_status.html' %}

    {% if bookings %}
        {% include 'booking/bookings_list_card.html' %}
    {% else %}
        <div class="text-center text-muted">Нет бронирований</div>
    {% endif %}

{% endblock  %}

app/booking/templates/booking/nav_replacer.html
{% extends 'nav_replacer.html' %}
{% block nav_replacer_title %}
    <a href="{% url 'booking:view' booking.pk %}" class="navbar-brand ps-2 py-0 me-0 text-truncate">
        <div class="text-truncate" style="font-size: 17px;">{{ booking.boat.name }}</div>
        <div style="font-size: 14px;">{{ booking.start_date|date:'d b. Y' }} - {{ booking.end_date|date:'d b. Y' }}</div>
    </a>
{% endblock %}

app/booking/templates/booking/nav_status.html
{% load static %}
<script type="text/javascript" src="{% static 'booking/js/nav_status.min.js' %}"></script>

<div class="container mb-3">
    <ul class="nav nav-pills nav-status flex-nowrap overflow-auto no-scrollbars">

        <li class="nav-item">
            <a class="nav-link text-nowrap {% if request.GET.status == 'pending' %}active{% endif %}" href="?status=pending">На рассмотрении</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-nowrap {% if request.GET.status == 'active' %}active{% endif %}" href="?status=active">Активные</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-nowrap {% if request.GET.status == 'done' %}active{% endif %}" href="?status=done">Завершенные</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-nowrap {% if not request.GET.status %}active{% endif %}" href="?">Все</a>
        </li>

    </ul>
</div>

app/booking/templates/booking/requests_list_card.html
{% load booking_extras %}

<div class="album mb-3">
    <div class="container">
        <div class="row row-cols-1 row-cols-xl-2 g-3">
            {% for req in requests %}
                <div class="col">
                    <div class="card box-shadow">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <a href="{% url 'booking:view' req.id %}" >
                                    {% include 'boat/carousel.html' with boat=req.boat %}
                                </a>    
                            </div>
                            <div class="col-md-8">
                                <div class="card-body d-flex flex-column">
                                    {% include 'booking/boat_card.html' with booking=req %}
                                    <div class="alert {{ req.status|get_status_color }} p-2 mb-2" role="alert">
                                        {% include 'booking/booking_data.html' with booking=req %}
                                    </div>
                                    <div class="dropdown mt-auto">
                                        <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuStatus{{ req.pk }}" data-bs-toggle="dropdown" aria-expanded="false">
                                            Действия
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuStatus{{ req.pk }}">
                                            {% if req.status == Status.PENDING %}
                                                <li>
                                                    <a class="dropdown-item accept-request" href="#" data-booking-id="{{ req.pk }}" data-status="{{ Status.ACCEPTED }}">
                                                        Подтвердить бронь
                                                    </a>
                                                </li>
                                            {% endif %}
                                            {% if req.status == Status.PREPAYMENT_REQUIRED %}
                                                <li>
                                                    <a class="dropdown-item accept-request" href="#" data-booking-id="{{ req.pk }}" data-status="{{ Status.ACCEPTED }}">
                                                        Оплата получена
                                                    </a>
                                                </li>
                                            {% endif %}
                                            {% if req.status in req.STATUSES_CAN_BE_DECLINED %}
                                                <li>
                                                    <a class="dropdown-item text-danger" href="#" data-booking-id="{{ req.pk }}" data-bs-toggle="modal" data-bs-target="#declineRequestModal">
                                                        Отменить бронь
                                                    </a>
                                                </li>
                                                <li><hr class="dropdown-divider"></li>      
                                            {% endif %}      
                                            <li><a class="dropdown-item" href="{% url 'chat:booking' req.pk %}?back={{ request.get_full_path }}">Чат</a></li>                           
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

app/booking/templates/booking/view.html
{% extends 'main.html' %}

{% load static %}
{% load booking_extras %}

{% block title %}Просмотр бронирования{% endblock %}

{% block content %}
    <div class="container-lg">
        <section class="jumbotron text-center">
            <h1 class="jumbotron-heading">Просмотр бронирования</h1>    
        </section>

        <div class="card mb-3">
            <div class="alert {{ booking.status|get_status_color }} bg-white mb-0" role="alert"> 
                {% include 'booking/booking_data.html' %}   
            </div>
        </div>

        {% include 'booking/view_boat.html' %}

        {% if booking.boat_info.term_content %}
            <div class="card mb-3 p-3">
                <h4>Условия аренды</h4>
                <div>
                    {{ booking.boat_info.term_content|safe }}
                </div>
            </div>
        {% endif %}

        {% include 'booking/spec.html' with spec=booking.spec total_sum=booking.total_sum %}
        
    </div>
    <div class="sticky-bottom action-footer mb-3">
        <div class="container-lg">
            <div class="card p-3">
                <div class="row g-2">
                    <div class="col col-lg-auto">
                        <a class="btn btn-primary w-100" href="{% url 'chat:booking' booking.pk %}" role="button">Чат</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

app/booking/templates/booking/view_boat.html
{% load l10n %}
{% load booking_extras %}
{% include 'leaflet.html' %}

{% with booking.boat_info.spec|boatspectoobj as spec %}
    <div class="row g-3 mb-3"> 
        <div class="col-lg">
            <div class="card h-100">
                {% if booking.boat_info.photo %}
                    <div class="card border-0 box-shadow text-end mb-3">
                        <img class="d-block w-100 card-img" src="{{ booking.boat_info.photo.url }}" />
                        <a type="button" class="carousel-control-full-screen" data-bs-toggle='modal' data-bs-target="#fullscreenViewer{{ booking.pk }}" title="Во весь экран">
                            <span class="carousel-control-full-screen-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Full screen</span>
                        </a>
                    </div>
                {% endif %}
                <div class="px-3 pb-3">
                    <h2>{{ spec.name }}</h2>   
                    <h4>{{ booking.boat_info.model.manufacturer.name }} {{ booking.boat_info.model.name }}</h4> 
                    <h4 class="text-muted">{{ booking.boat_info.get_type_display }}</h4>   
                    {% include 'booking/boat_location.html' %}
                </div>
            </div>
        </div>

        <div class="col-lg">     
            <div class="card h-100 p-3">      
                <div class="row row-cols-3 gx-3">   
                    <div class="col-12">
                        <h5>Основная информация</h5>
                    </div>                
                    <div class="col">
                        <p class="text-muted">
                            <span class="d-block">Длина, м.</span><span class="text-primary">{{ spec.length }}</span>
                        </p>
                    </div>
                    <div class="col">
                        <p class="text-muted">
                            <span class="d-block">Ширина, м.</span><span class="text-primary">{{ spec.width }}</span>
                        </p>
                    </div>
                    <div class="col">
                        <p class="text-muted">
                            <span class="d-block">Осадка, м.</span><span class="text-primary">{{ spec.draft }}</span>
                        </p>
                    </div>                      
                    <div class="col">
                        <p class="text-muted">
                            <span class="d-block">Год выпуска</span><span class="text-primary">{{ spec.issue_year|default:"-"|unlocalize }}</span>
                        </p>
                    </div>
                    <div class="col-8">
                        <p class="text-muted">
                            <span class="d-block">Вместимость</span><span class="text-primary">{{ spec.capacity }}</span>
                        </p>
                    </div>
                
                    <div class="col-12">
                        <h5>Двигатели</h5>
                    </div>                 
                    <div class="col">
                        <p class="text-muted">
                            <span class="d-block">Кол-во</span><span class="text-primary">{{ spec.motor.motor_amount|default:"-" }}</span>
                        </p>
                    </div>
                    <div class="col-8">
                        <p class="text-muted">
                            <span class="d-block">Мощность, л.с.</span><span class="text-primary">{{ spec.motor.motor_power|default:"-" }}</span>
                        </p>
                    </div>                  
                
                    <div class="col-12">
                        <h5>Удобства</h5>
                    </div>                 
                    <div class="col">
                        <p class="text-muted">
                            <span class="d-block">Спальные места</span><span class="text-primary">{% get_berth_amount spec %}</span>
                        </p>
                    </div>
                    <div class="col mt-auto">
                        <p class="text-muted">
                            <span class="d-block">Каюты</span><span class="text-primary">{{ spec.comfort.cabin_amount|default:"-" }}</span>
                        </p>
                    </div>           
                    <div class="col mt-auto">
                        <p class="text-muted">
                            <span class="d-block">WC</span><span class="text-primary">{{ spec.comfort.bathroom_amount|default:"-" }}</span>
                        </p>
                    </div>     
                    
                    <div class="col-12">
                        <h5>Владелец</h5>
                    </div>  
                    <div class="col-12 mb-3">
                        {% if booking.boat_info.owner.avatar_sm %}
                            <img height="32" width="32" src="{{ booking.boat_info.owner.avatar_sm.url }}" class="of-cover rounded-circle bg-light">
                        {% endif %}
                        <span class="text-muted align-middle">{{ booking.boat_info.owner.first_name }}</span>
                    </div>
                </div>
            </div>
        </div>           
    </div>
    {% include 'modal_map.html' %}

    {% if spec.text %}
        <div class="card p-3 mb-3">
            <h4 class="mb-3">Описание</h4>
            {{ spec.text|default_if_none:""|linebreaks }}
        </div>
    {% endif %}

{% endwith %}

{% with booking.pk|stringformat:'s' as booking_pk_str %}
    {% include 'boat/fullscreen_viewer.html' with fullscreen_viewer_id='fullscreenViewer'|add:booking_pk_str photo=booking.boat_info.photo %}
{% endwith %}