app/boat/urls.py
from django.urls import include, path

from . import views

app_name = 'boat'

apiurlpatterns = [
    path('create/', views.create, name='api_create'),
    path('update/<int:pk>/', views.update, name='api_update'),
    path('delete/<int:pk>/', views.delete, name='api_delete'),

    path('get_files/<int:pk>/', views.get_files, name='api_get_files'),
    path('calc_booking/<int:pk>/', views.calc_booking,
         name='api_calc_booking'),
    path('set_status/<int:pk>/', views.set_status, name='api_set_status'),
    path('get_models/<int:pk>/', views.get_models, name='api_get_models'),
    path('switch_fav/<int:pk>/', views.switch_fav, name='api_switch_fav')
]

urlpatterns = [
    path('my_boats/', views.my_boats, name='my_boats'),
    path('boats_on_moderation/', views.boats_on_moderation,
         name='boats_on_moderation'),
    path('favs/', views.favs, name='favs'),

    path('create/', views.create, name='create'),
    path('update/<int:pk>/', views.update, name='update'),
    path('booking/<int:pk>/', views.booking, name='booking'),
    path('view/<int:pk>/', views.view, name='view'),

    path('moderate/<int:pk>/', views.moderate, name='moderate'),
    path('accept/<int:pk>/', views.accept, name='accept'),
    path('reject/<int:pk>/', views.reject, name='reject'),
    path('search_boats/', views.search_boats, name='search_boats'),

    path('create_tariff/', views.create_tariff, name='create_tariff'),
    path('update_tariff/<int:pk>/', views.update_tariff, name='update_tariff'),
    path('delete_tariff/<int:pk>/', views.delete_tariff, name='delete_tariff'),

    path('terms/', views.terms, name='terms'),
    path('create_term/', views.create_term, name='create_term'),
    path('update_term/<int:pk>/', views.update_term, name='update_term'),
    path('delete_term/<int:pk>/', views.delete_term, name='delete_term'),

    path('api/', include(apiurlpatterns))
]

app/booking/urls.py
from django.urls import include, path

from . import views

app_name = 'booking'

apiurlpatterns = [
    path('set_status/<int:pk>/', views.set_status, name='api_set_status'),
    path('set_request_status/<int:pk>/',
         views.set_request_status, name="api_set_request_status")
]

urlpatterns = [
    path('my_bookings', views.my_bookings, name='my_bookings'),
    path('confirm/<int:boat_pk>/', views.confirm, name='confirm'),
    path('create/', views.create, name='create'),
    path('requests', views.requests, name='requests'),
    path('view/<int:pk>/', views.view, name='view'),
    path('all/', views.all, name='all'),
    path('api/', include(apiurlpatterns))
]

app/chat/urls.py
from django.urls import include, path

from . import views

app_name = 'chat'

apiurlpatterns = [
    path('send_message_booking/<int:pk>/', views.send_message_booking),
    path('get_new_messages_booking/<int:pk>/', views.get_new_messages_booking),

    path('get_new_messages_boat/<int:pk>/', views.get_new_messages_boat),
    path('send_message_boat/<int:pk>/', views.send_message_boat),

    path('get_new_messages/', views.get_new_messages),
    path('send_message/', views.send_message),

    path('get_new_support_messages/<int:user_pk>/',
         views.get_new_support_messages),
    path('send_support_message/<int:user_pk>/', views.send_support_message)
]

urlpatterns = [
    path('booking/<int:pk>/', views.booking, name='booking'),
    path('boat/<int:pk>/', views.boat, name='boat'),
    path('message/', views.message, name='message'),
    path('list/', views.list, name='list'),
    path('support/', views.support, name='support'),
    path('support_chat/<int:user_pk>/',
         views.support_chat, name='support_chat'),
    path('read_all/', views.read_all, name='read_all'),

    path('api/', include(apiurlpatterns))
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from boat import urls as boat_urls
from booking import urls as booking_urls
from chat import urls as chat_urls
from portal import urls as portal_urls
from telegram_bot import urls as telegram_bot_urls
from user import urls as user_urls

from . import views

urlpatterns = [
    path('', views.index),
    path(f'{settings.ADMIN_URL}/', admin.site.urls),

    path('user/', include(user_urls)),
    path('boats/', include(boat_urls)),
    path('bookings/', include(booking_urls)),
    path('telegram_bot/', include(telegram_bot_urls)),
    path('chat/', include(chat_urls)),
    path('portal/', include(portal_urls)),

    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/booking/models.py
import datetime

from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from boat.models import Base, Boat, Model
from user.models import User

from .exceptions import (BookingDateRangeException,
                         BookingDuplicatePendingException)


class BookingQuerySet(models.QuerySet):
    """QuerySet бронирования."""
    def in_range(self, start_date: datetime.date, end_date: datetime.date):
        """Отфильтровать за период.

        Args:
            start_date: дата начала
            end_date: дата окончания

        """
        return self.filter(
            Q(start_date__range=(start_date, end_date)) |
            Q(end_date__range=(start_date, end_date)) |
            Q(start_date__lt=start_date, end_date__gt=end_date)
        )

    def blocked_in_range(self,
                         start_date: datetime.date, end_date: datetime.date):
        """Отфильтровать заблокированные бронирования за период.

        Args:
            start_date: дата начала
            end_date: дата окончания

        """
        return self.filter(status__in=Booking.BLOCKED_STATUSES) \
                   .in_range(start_date, end_date)

    def filter_by_status(self, status: str):
        """Отфильтровать бронирования по статусу.

        Args:
            status: статус

        """
        mapping = {
            'pending': Booking.PENDING_STATUSES,
            'active': Booking.ACTIVE_STATUSES,
            'done': Booking.DONE_STATUSES,
        }
        statuses = mapping.get(status)
        if not statuses:
            return self
        return self.filter(status__in=statuses)


class Booking(models.Model):
    """Модель бронирования."""

    class Status(models.IntegerChoices):
        """Статусы бронирования."""
        PENDING = 0, _("Ожидание подтверждения")
        DECLINED = -1, _("Отменено")
        ACCEPTED = 1, _("Подтверждено")
        PREPAYMENT_REQUIRED = 2, _("Ожидание предоплаты")
        ACTIVE = 3, _("Активно")
        DONE = 4, _("Завершено")

    BLOCKED_STATUSES = [Status.ACCEPTED,
                        Status.PREPAYMENT_REQUIRED,
                        Status.ACTIVE,
                        Status.DONE]

    PENDING_STATUSES = [Status.PENDING, ]
    ACTIVE_STATUSES = [Status.ACCEPTED,
                       Status.PREPAYMENT_REQUIRED,
                       Status.ACTIVE]

    DONE_STATUSES = [Status.DONE, Status.DECLINED]

    STATUSES_CAN_BE_DECLINED = [Status.PENDING, Status.PREPAYMENT_REQUIRED]

    boat = models.ForeignKey(
        Boat, on_delete=models.PROTECT, related_name='bookings')
    renter = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='bookings')
    status = models.IntegerField(
        choices=Status.choices, default=Status.PENDING)

    start_date = models.DateField()
    end_date = models.DateField()
    total_sum = models.DecimalField(max_digits=8, decimal_places=2)
    spec = models.JSONField(null=True, blank=True)

    objects = models.Manager.from_queryset(BookingQuerySet)()

    def clean(self):
        if self.pk is None:
            accepted_bookings_exist = \
                Booking.objects \
                       .filter(boat=self.boat) \
                       .blocked_in_range(self.start_date, self.end_date) \
                       .exists()

            if accepted_bookings_exist:
                raise BookingDateRangeException()

            duplicate_bookings_exist = Booking.objects.filter(
                boat=self.boat,
                renter=self.renter,
                status=self.Status.PENDING
            ).in_range(self.start_date, self.end_date).exists()

            if duplicate_bookings_exist:
                raise BookingDuplicatePendingException()

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Booking, self).save(*args, **kwargs)

    def __str__(self):
        return f'Бронь № {self.pk} - {self.boat}'


class Prepayment(models.Model):
    """Модель предоплаты."""
    booking = models.OneToOneField(
        Booking, primary_key=True, on_delete=models.CASCADE)
    until = models.DateTimeField()


class BoatInfo(models.Model):
    """Модель информации о лодке."""
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE,
                                   primary_key=True, related_name="boat_info")
    prepayment_required = models.BooleanField()
    term_content = models.TextField(null=True, blank=True)

    owner = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="requests")
    model = models.ForeignKey(
        Model, on_delete=models.PROTECT, related_name="bookings")
    type = models.IntegerField(choices=Boat.Type.choices)
    base = models.ForeignKey(Base, on_delete=models.PROTECT,
                             related_name="bookings", null=True, blank=True)
    photo = models.ImageField()
    spec = models.JSONField(null=True, blank=True)


class BoatInfoCoordinates(models.Model):
    """Модель информации о координатах лодки."""
    boat_info = models.OneToOneField(BoatInfo, on_delete=models.CASCADE,
                                     primary_key=True,
                                     related_name="coordinates")
    lon = models.DecimalField(max_digits=9, decimal_places=6)
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    address = models.TextField()
    state = models.CharField(max_length=255, db_index=True)

app/boat/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Tariff, Term


class TariffForm(ModelForm):
    """Форма тарифа."""

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(TariffForm, self).__init__(*args, **kwargs)

    def clean_boat(self):
        """Валидировать лодку.

        Returns:
            Boat: лодка

        Raises:
            ValidationError: лодка не найдена

        """
        boat = self.cleaned_data.get('boat')
        if boat and (boat.owner != self.request.user or not boat.is_active):
            raise ValidationError('Не найдена')
        return boat

    class Meta:
        model = Tariff
        exclude = ('weight',)


class TermForm(ModelForm):
    """Форма шаблона условий."""
    class Meta:
        model = Term
        exclude = ('user',)

app/boat/templates/boat/boats_on_moderation.html
{% extends 'main.html' %}

{% load static %}

{% block title %}Модерация лодок{% endblock  %}

{% block content %}   
     
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Модерация лодок</h1>
        </div>
    </section>

    {% if boats %}
        {% include 'leaflet.html' %}   
        <div class="album">
            <div class="container">
                <div class="row g-4">
                    {% for boat in boats %}
                        <div class="col-lg-4 col-md-4">
                            <div class="card box-shadow h-100 rounded-3">
                                <a href="{% url 'boat:moderate' boat.id %}" >
                                    {% include 'boat/carousel.html' %}
                                </a>    
                                <div class="card-body d-flex flex-column">
                                    {% include 'boat/card.html' %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% include 'modal_map.html' %}
    {% else %}
        <div class="text-center text-muted">Нет лодок для модерации</div>
    {% endif %}
{% endblock  %}

app/boat/templates/boat/card.html
{% load l10n %}
{% load boat_extras %}

<h5 class="card-title">{{ boat.get_full_name }}</h5>     
<h6 class="card-subtitle mb-1 text-muted">{{ boat.get_type_display }}</h6>
{% include 'boat/location.html' %}
<div class="container text-muted px-0 mt-3 small">
    <div class="row">
        <div class="col-2 pe-0">Год</div>
        <div class="col-4 ps-0 text-end text-primary">{{ boat.issue_year|default:"-"|unlocalize }}</div>
        <div class="col-3 pe-0">Двигатель</div>
        <div class="col-3 ps-0 text-end text-primary">
            {% if boat.is_motor_boat %}
                {% if boat.motor_boat.motor_amount > 1 %}{{ boat.motor_boat.motor_amount }}&nbsp;x&nbsp;{% endif %}{{ boat.motor_boat.motor_power.normalize }} л.с.
            {% else %}-{% endif %}
        </div>

        <div class="col-4 pe-0">Длина</div>
        <div class="col-2 ps-0 text-end text-primary">{{ boat.length }} м.</div>
        <div class="col-3 pe-0">Осадка</div>
        <div class="col-3 ps-0 text-end text-primary">{{ boat.draft }} м.</div>

        <div class="col-4 pe-0">Спальных мест</div>
        <div class="col-2 ps-0 text-end text-primary">{% get_berth_amount boat %}</div>
        <div class="col-3 pe-0">Кают</div>
        <div class="col-3 ps-0 text-end text-primary">{{ boat.comfort_boat.cabin_amount|default:'-' }}</div>

        <div class="col-4 pe-0">WC</div>
        <div class="col-2 ps-0 text-end text-primary">{{ boat.comfort_boat.bathroom_amount|default:'-' }}</div>
    </div>
</div>

app/boat/templates/boat/create_term.html
{% extends 'main.html' %}

{% load static %}

{% block title %}Добавление условий аренды{% endblock %}

{% block content %}
    <div class="container-lg">
        <section class="jumbotron text-center">   
            <h1 class="jumbotron-heading">Добавление условий аренды</h1>    
        </section>
    </div>

    <form method="post" action="{% url 'boat:create_term' %}" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="container-lg">
            {% include 'boat/term_form.html' %}             
        </div>
        <div class="sticky-bottom action-footer mb-3">
            <div class="container-lg">
                <div class="card p-3">
                    <div class="row">
                        <div class="col col-lg-auto">
                            <button type="submit" class="btn btn-primary w-100">Сохранить</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

app/boat/templates/boat/delete_modal.html
<div id="confirmDeleteModal" class="modal" data-boat-id="{{ boat.id }}" tabindex="-1" role="dialog" aria-labelledby="confirmDeletionModalLabel" style="display: none">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 380px;">
        <div class="modal-content box-shadow">
            <div class="modal-body p-4">
                <h5 class="text-center mb-3">Удалить лодку?</h5>     
                <p>Все цены и фотографии так же будут удалены.</p>
                <p>Бронирования, находящиеся на рассмотрении, будут отменены.</p> 
                <hr/>                     
                <p class="mb-0 text-danger">Вы не сможете удалить лодку, если есть подтвержденные бронирования.</p>         
            </div>
            <div class="modal-footer flex-nowrap p-0">
                <button id="btnConfirmDelete" type="button" class="btn btn-l btn-link fs-6 text-decoration-none text-danger col-6 m-0 rounded-0 border-end">
                    <strong>Да, удалить</strong>
                </button>
                <button type="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 m-0 rounded-0" data-bs-dismiss="modal">Отмена</button>               
            </div>
        </div>
    </div>
</div>

app/boat/templates/boat/popup_create_term.html
{% extends 'main.html' %}

{% load static %}

{% block title %}Добавление условий аренды{% endblock %}

{% block nav %}{% endblock %}

{% block content %}
    <div class="container-lg">
        <section class="jumbotron text-center">   
            <h1 class="jumbotron-heading">Добавление условий аренды</h1>    
        </section>
    </div>

    <form method="post" action="{% url 'boat:create_term' %}" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="container-lg">
            {% include 'boat/term_form.html' %}             
        </div>
        <div class="sticky-bottom action-footer mb-3">
            <div class="container-lg">
                <div class="card p-3">
                    <div class="row g-2">      
                        <div class="col col-lg-auto">
                            <button type="submit" class="btn btn-primary w-100">Сохранить</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block footer %}{% endblock %}

app/boat/templates/boat/search_boats.html
{% extends 'main.html' %}
{% load static %}
{% load l10n %}
{% load boat_extras %}

{% block title %}Поиск лодки{% endblock %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'boat/css/search_boats.css' %}">
    <script type="text/javascript" src="{% static 'boat/js/search_boats.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/air-datepicker.css' %}">
    <script type="text/javascript" src="{% static 'js/air-datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'boat/js/switch_fav.min.js' %}"></script>

    <div class="container-md">
        <section class="jumbotron text-center ">      
            <h1 class="jumbotron-heading">Поиск лодки</h1>
        </section>
    </div>

    <div class="sticky-top action-header d-lg-none">
        <div class="container-lg">
            <div class="card p-3">
                <div class="row g-2">            
                    <div class="col col-lg-auto">
                        <button class="btn btn-outline-primary w-100 position-relative" type="button" 
                            data-bs-toggle="offcanvas" data-bs-target="#offcanvasBoatFilter" aria-controls="offcanvasBoatFilter">Фильтр
                            {% get_filter_count request as filter_count %}
                            {% if filter_count > 0 %}
                                <span class="badge bg-danger">{{ filter_count }}</span>
                            {% endif %}
                        </button>                        
                    </div>
                </div>
            </div>
        </div>
    </div>
        
    <div class="container-md my-3">
        {% include 'paginator.html' with class="mb-3" %}
        <div class="row">
            {% if boats %}   
                <div class="col">
                    {% include 'leaflet.html' %}
                    <div class="album">
                        <div class="row row-cols-1 justify-content-end g-3">
                            {% for boat in boats %}
                                <div class="col">
                                    <div class="card box-shadow h-100 rounded-3">
                                        <div class="row g-0">
                                            <div class="col-md-4">
                                                <a href="{% url 'boat:booking' boat.id %}?dateFrom={{ request.GET.dateFrom }}&dateTo={{ request.GET.dateTo }}">
                                                    {% include 'boat/carousel.html' %}
                                                </a>
                                            </div>
                                            <div class="col-md-8">
                                                <div class="card-body d-flex flex-column">
                                                    {% include 'boat/card.html' %}
                                                    <div class="row align-items-center mt-2 mb-2">
                                                        {% if user.is_authenticated %}
                                                            <div class="col-auto">
                                                                <button type="button" class="btn px-0 btn-link btn-fav-icon no-focus" data-pk="{{ boat.pk }}">
                                                                    {% if boat.in_fav %}
                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-heart-fill text-danger" viewBox="0 0 16 16">
                                                                            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                                                        </svg>
                                                                    {% else %}
                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-heart text-primary" viewBox="0 0 16 16">
                                                                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                                                                        </svg>
                                                                    {% endif %}
                                                                </button>
                                                            </div>
                                                        {% endif %}
                                                        <div class="col">
                                                            <div class="text-success fs-3 text-end mb-1">от {{ boat.actual_tariffs.0.price_per_day }}&nbsp;₽ / день</div>
                                                        </div>
                                                    </div>
                                                </div>    
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div> 
            {% else %}
                <div class="col text-center">
                    <h4 class="mt-3">Нет подходящих лодок</h4>
                    <p>Попробуйте смягчить условия поиска или изменить период</p>
                    <button id="btnNotFoundClearFilter" class="btn btn-outline-danger mb-3" type="button">Сброcить фильтр</button>
                </div>
            {% endif %}
            <div class="col-auto" style="min-width: 354px; max-width: 354px">
                {% include 'boat/filter.html' %}
            </div>
            
        </div>
        {% include 'paginator.html' with class="mt-3" %}
    </div>

    {% include 'modal_map.html' %}
{% endblock %}

app/boat/templates/boat/tariffs_list.html
{% load boat_extras %}

{% if tariffs %}
    <div class="table-responsive">
        <table class="table text-nowrap">
            <thead>
                <tr>
                    <th>Название</th>
                    {% if show_active_column %}<th>Активен</th>{% endif %}
                    <th>Цена</th>
                    <th>Продолжительность</th>
                    <th>Срок аренды</th>
                    <th>Дни начала тарифа</th>
                </tr>
            </thead>
            <tbody>

                {% for tariff in tariffs %}
                    {% get_duration_display tariff as duration_display %}

                    {% ifchanged tariff.start_date tariff.end_date %}
                        <tr>
                            <td class="px-0" colspan="{% if show_active_column %}6{% else %}5{% endif %}">
                                <h6 class="badge text-bg-light p-2 mb-0 w-100 text-start">{{ tariff.start_date }} - {{ tariff.end_date }}</h6>
                            </td>
                        </tr>      
                    {% endifchanged  %}
                    <tr>
                        {% if show_edit_href %}
                            <td><a href="{% url 'boat:update_tariff' tariff.pk %}">{{ tariff.name }}</a></td>
                        {% else %}
                            <td>{{ tariff.name }}</td>
                        {% endif %}
                        
                        {% if show_active_column %}
                            <td class="{% if tariff.active %}text-success{% else %}text-danger{% endif %}">{{ tariff.active|yesno:"Да,Нет" }}</td>
                        {% endif %}
                        
                        <td>{{ tariff.price }}</td>
                        <td>{{ duration_display|capfirst }}</td>
                        <td>{% get_min_display tariff %}</td>
                        <td>{% get_weekdays_display tariff %}</td>
                    </tr>      
                {% endfor %} 

            </tbody>   
        </table>
    </div>
{% endif %}

app/boat/templates/boat/terms.html
{% extends 'main.html' %}

{% load static %}
{% load boat_extras %}

{% block title %}Условия аренды{% endblock  %}

{% block content %}    
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading mb-1">Условия аренды</h1>
        </div>
    </section>

    <div class="album mb-3">
        <div class="container">
            <div class="row row-cols-1 row-cols-xl-4 g-3">
                {% for term in terms %}
                    <div class="col">
                        <div class="card box-shadow h-100 rounded-3">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title"><a href="{% url 'boat:update_term' pk=term.pk %}" class="stretched-link">{{ term.name }}</a></h5>
                                <p class="card-text">
                                {% if term.boats.all.exists %}
                                    Используются в {{ term.boats.all.count }} {% countcase term.boats.all.count 'лодке' 'лодках' 'лодках' %}
                                {% else %}
                                    Не используются
                                {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            
        </div>
    </div>

    <div class="sticky-bottom action-footer mb-3">
        <div class="container-lg">
            <div class="card p-3">
                <div class="row g-2">            
                    <div class="col col-lg-auto">
                        <a href="{% url 'boat:create_term' %}" class="btn btn-primary w-100">Добавить условие</a>                       
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

app/boat/templates/boat/view.html
{% extends 'main.html' %}

{% load static %}

{% block title %}Просмотр лодки{% endblock %}

{% block content %}
    <div class="container-lg">
        <section class="jumbotron text-center">
            <h1 class="jumbotron-heading">Просмотр лодки</h1>    
        </section>
        {% include 'boat/alert_boat_declined.html' %}
        {% include 'boat/view_base.html' %}     
    </div>

    <div class="container-lg mb-3">
        <div class="card p-3 mb-3">
            <h4 id="tariffs" class="mb-3">Тарифы</h4>
            {% include 'boat/tariffs_list.html' with tariffs=boat.tariffs.all show_active_column=True show_edit_href=True %}  
            
            <div class="row">
                <div class="col col-lg-auto">
                    <a class="btn btn-primary w-100" href="{% url 'boat:create_tariff' %}?boat_pk={{ boat.pk }}" >Добавить тариф</a>  
                </div>
            </div>
        </div>
    </div>

    <div class="sticky-bottom action-footer mb-3">
        <div class="container-lg mb-3">
            <div class="card p-3">
                <div class="row g-2">
                    <div class="col-6 col-lg-auto">
                        <a class="btn btn-primary w-100" href="{% url 'boat:update' boat.pk %}" role="button">Редактировать</a>
                    </div>
                    <div class="col-6 col-lg-auto">
                        <a class="btn btn-outline-primary w-100 text-truncate" href="{% url 'chat:boat' boat.pk %}?back={{ request.path }}">Чат</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

app/boat/templates/boat/view_base_info.html
{% load l10n %}
{% load static %}
{% load boat_extras %}

{% include 'leaflet.html' %}

{% if boat.files.exists %}
    <script type="text/javascript" src="{% static 'boat/js/img_viewer.min.js' %}"></script>
    <div class="card border-0 text-end shadow-none mb-3">
        <img class="d-block w-100 card-img card-img-main" src="{{ boat.files.first.file.url }}" />
        <a type="button" class="carousel-control-full-screen" data-bs-toggle='modal' data-bs-target="#fullscreenViewer{{ boat.pk }}" title="Во весь экран">
            <span class="carousel-control-full-screen-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Full screen</span>
        </a>
    </div>  
    {% if boat.files.count > 1 %}
        <div class="row g-1 px-3 mb-3">
            {% for file in boat.files.all %}
                <div class="col-auto">
                    <img class="card-img card-img-small {% if forloop.counter0 == 0  %}active{% endif %}" src="{{ file.file.url }}" />
                </div>
            {% endfor %}
        </div>  
    {% endif %}       
{% endif %}

<div class="px-3 pb-3">
    <h2>{{ boat.name }}</h2>   
    <h4>{{ boat.model.manufacturer.name }} {{ boat.model.name }}</h4> 
    <h4 class="text-muted">{{ boat.get_type_display }}</h4>
    {% include 'boat/location.html' %}
</div>

{% include 'modal_map.html' %}

{% with boat.pk|stringformat:'s' as boat_pk_str %}
    {% include 'boat/fullscreen_viewer.html' with fullscreen_viewer_id='fullscreenViewer'|add:boat_pk_str photos=boat.files.all %}
{% endwith %}