app/boat/urls.py
from django.urls import include, path

from . import views

app_name = 'boat'

apiurlpatterns = [
    path('create/', views.create, name='api_create'),
    path('update/<int:pk>/', views.update, name='api_update'),
    path('delete/<int:pk>/', views.delete, name='api_delete'),

    path('get_files/<int:pk>/', views.get_files, name='api_get_files'),
    path('calc_booking/<int:pk>/', views.calc_booking,
         name='api_calc_booking'),
    path('set_status/<int:pk>/', views.set_status, name='api_set_status'),
    path('get_models/<int:pk>/', views.get_models, name='api_get_models'),
    path('switch_fav/<int:pk>/', views.switch_fav, name='api_switch_fav')
]

urlpatterns = [
    path('my_boats/', views.my_boats, name='my_boats'),
    path('boats_on_moderation/', views.boats_on_moderation,
         name='boats_on_moderation'),
    path('favs/', views.favs, name='favs'),

    path('create/', views.create, name='create'),
    path('update/<int:pk>/', views.update, name='update'),
    path('booking/<int:pk>/', views.booking, name='booking'),
    path('view/<int:pk>/', views.view, name='view'),

    path('moderate/<int:pk>/', views.moderate, name='moderate'),
    path('accept/<int:pk>/', views.accept, name='accept'),
    path('reject/<int:pk>/', views.reject, name='reject'),
    path('search_boats/', views.search_boats, name='search_boats'),

    path('create_tariff/', views.create_tariff, name='create_tariff'),
    path('update_tariff/<int:pk>/', views.update_tariff, name='update_tariff'),
    path('delete_tariff/<int:pk>/', views.delete_tariff, name='delete_tariff'),

    path('terms/', views.terms, name='terms'),
    path('create_term/', views.create_term, name='create_term'),
    path('update_term/<int:pk>/', views.update_term, name='update_term'),
    path('delete_term/<int:pk>/', views.delete_term, name='delete_term'),

    path('api/', include(apiurlpatterns))
]

app/booking/urls.py
from django.urls import include, path

from . import views

app_name = 'booking'

apiurlpatterns = [
    path('set_status/<int:pk>/', views.set_status, name='api_set_status'),
    path('set_request_status/<int:pk>/',
         views.set_request_status, name="api_set_request_status")
]

urlpatterns = [
    path('my_bookings', views.my_bookings, name='my_bookings'),
    path('confirm/<int:boat_pk>/', views.confirm, name='confirm'),
    path('create/', views.create, name='create'),
    path('requests', views.requests, name='requests'),
    path('view/<int:pk>/', views.view, name='view'),
    path('all/', views.all, name='all'),
    path('api/', include(apiurlpatterns))
]

app/chat/urls.py
from django.urls import include, path

from . import views

app_name = 'chat'

apiurlpatterns = [
    path('send_message_booking/<int:pk>/', views.send_message_booking),
    path('get_new_messages_booking/<int:pk>/', views.get_new_messages_booking),

    path('get_new_messages_boat/<int:pk>/', views.get_new_messages_boat),
    path('send_message_boat/<int:pk>/', views.send_message_boat),

    path('get_new_messages/', views.get_new_messages),
    path('send_message/', views.send_message),

    path('get_new_support_messages/<int:user_pk>/',
         views.get_new_support_messages),
    path('send_support_message/<int:user_pk>/', views.send_support_message)
]

urlpatterns = [
    path('booking/<int:pk>/', views.booking, name='booking'),
    path('boat/<int:pk>/', views.boat, name='boat'),
    path('message/', views.message, name='message'),
    path('list/', views.list, name='list'),
    path('support/', views.support, name='support'),
    path('support_chat/<int:user_pk>/',
         views.support_chat, name='support_chat'),
    path('read_all/', views.read_all, name='read_all'),

    path('api/', include(apiurlpatterns))
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from boat import urls as boat_urls
from booking import urls as booking_urls
from chat import urls as chat_urls
from portal import urls as portal_urls
from telegram_bot import urls as telegram_bot_urls
from user import urls as user_urls

from . import views

urlpatterns = [
    path('', views.index),
    path(f'{settings.ADMIN_URL}/', admin.site.urls),

    path('user/', include(user_urls)),
    path('boats/', include(boat_urls)),
    path('bookings/', include(booking_urls)),
    path('telegram_bot/', include(telegram_bot_urls)),
    path('chat/', include(chat_urls)),
    path('portal/', include(portal_urls)),

    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/portal/urls.py
from django.urls import re_path

from . import views

app_name = 'portal'

urlpatterns = [
    re_path(r'.*', views.portal, name="portal"),
]

app/user/urls.py
from django.urls import include, path

from . import views

app_name = "user"

urlapipatterns = [
    path('update_avatar/', views.update_avatar, name='api_update_avatar'),
    path('send_verification_email/<email>/',
         views.send_verification_email, name="send_verification_email"),
    path('send_restore_password_email/', views.send_restore_password_email,
         name="send_restore_password_email"),
    path('generate_telegram_code/', views.generate_telegram_code,
         name='generate_telegram_code')
]

urlpatterns = [
     path('login/', views.login, name='login'),
     path('logout/', views.logout, name='logout'),
     path('register/', views.register, name='register'),
     path('update/', views.update, name='update'),
     path('restore_password/', views.restore_password,
          name='restore_password'),

     path('verify/<token>/', views.verify, name='verify'),
     path('change_password/<token>/', views.change_password,
          name='change_password'),
     path('support/', views.support, name='support'),
     path('api/', include(urlapipatterns))
]

app/templates/chevron_down.html
<div class="position-absolute start-50 translate-middle-x bottom-0 mb-3">
    <a href="{{ href }}" title="{{ title }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="#fff" class="bi bi-chevron-down" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
        </svg>
    </a>
</div>

app/templates/footer.html
<footer class="sb-secondary-bg text-muted py-3 border-top" style="height: 100px">
    <div class="container-md text-center">SHAREBOAT.RU 2022</div>
</footer>

app/templates/form_errors.html
{% if form.errors %}
    <div class="alert alert-danger">
        <ul class="list-group list-group-flush">            
            {% for error in form.non_field_errors %}
                <li class="list-group-item list-group-item-danger">{{ error }}</li>
            {% endfor %}

            {% for field in form %}
                {% if field.errors %}
                    <li class="list-group-item list-group-item-danger"><strong>{{ field.label }}</strong> {{ field.errors|join:'; '|lower }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

app/templates/index.html
{% extends 'main.html' %}
{% load static %}
{% load extras %}



{% block nav %}
    {% include 'nav.html' with transparent=True %}
{% endblock %}

{% block content %}
    <script type="text/javascript" src="{% static 'js/index.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/air-datepicker.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/air-datepicker.css' %}">
    
    <section id="search">
        <div class="container-md w-100 pt-5">
            <div class="text-white text-center">
                <h1 class="display-6 mb-5">Найди лодку для незабываемого путешествия!</h1>
            </div>
            <div class="d-flex justify-content-center mb-5">
                <div class="mw-900" style="width: 900px;">
                    <form id="formSearch" action="{% url 'boat:search_boats' %}" method="get" c>
                        <input id="hiddenDateFrom" name="dateFrom" type="hidden" />
                        <input id="hiddenDateTo" name="dateTo" type="hidden" />
                        <div class="row row-cols-1 row-cols-lg-3 g-3 p-0">
                            <div class="col">
                                <div class="form-floating">                 
                                    <input id="dpRange" type="text" placeholder="Укажите период" class="form-control false-readonly" autocomplete="off" readonly />
                                    <label>Период бронирования</label>
                                    <div class="invalid-tooltip">Укажите период бронирования</div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-floating">
                                    <select class="form-select" id="stateSelect" name="state">
                                        <option selected value="">Любое</option>
                                        {% for state in states %}
                                            <option {% if request.GET.state == state %}selected{% endif %} value="{{ state }}">{{ state }}</option>
                                        {% endfor %}
                                    </select>
                                    <label for="stateSelect">Местоположение</label>
                                </div>
                            </div>
                            <div class="col">
                                <button class="btn btn-lg btn-warning w-100 h-100" type="submit">Найти</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="text-center text-white lead d-flex justify-content-center">
                <div style="width: 900px;">
                    <p>Цифровая платформа для удобной аренды лодок, которая объединяет капитанов, владельцев судов и другие заинтереснованные стороны</p>
                    <p>Наша цель - помочь развитию водного туризма в России</p>
                </div>
            </div>
        </div>
        {% include 'chevron_down.html' with href='#about' title='Яхтинг - это доступно' %}
    </section>

    <div class="bg-white text-black">
        <section id="about" class="container-md text-center d-flex align-items-center mw-900">
            <div>
                <h1 class="mb-3">Яхтинг - это доступно</h1>
                <p class="lead mb-0">Мы хотим повысить доступность самостоятельного водного туризма.<br>Не обязательно владеть яхтой или катером, чтобы наслаждаться величием природы с воды.</h>
            </div>
        </section>
    </div>

    <section id="youcando" class="py-5">
        <div class="container-md text-white py-5 mw-900" >
            <h1 class="text-center mb-3">С помощью SHAREBOAT.RU вы сможете:</h1>
            <ul class="lead">
                <li class="pt-3">Исследовать недоступные сухопутным туристам уединённые природные достопримечательности.</li>
                <li class="pt-3">Насладиться яхтингом без инвестиций в собственную лодку и необходимости заботиться о хранении, обслуживании и ремонте лодки.</li>
                <li class="pt-3">Попробовать разные виды лодок, чтобы понять, какая наиболее подходит вам.</li>
            </ul>
        </div>
    </section>

    <div class="bg-white text-black">
        <section id="howitworks" class="container-md d-flex align-items-center overflow-hidden pb-5 mw-900">
            <div class="w-100 mb-5">
                <h1 class="text-center my-5">Как работает SHAREBOAT.RU</h1>
                {% for step in steps %}
                    <div class="step">
                        <h5 class="text-center scale px-3">{{ step.0 }}</h5>
                        <p class="lead text-center">{{ step.1 }}</p>
                        {% if not forloop.last %}
                            <div class="text-center my-3">
                                <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="#ffc107" class="bi bi-arrow-down" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/>
                                </svg>
                            </div>    
                        {% endif %} 
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>

    <section id="clients" class="py-5">
        <div class="container-md text-white py-5 mw-900" >
            <h1 class="text-center mb-5">Кому будет полезен наш сервис</h1>
            <h4 class="text-center mb-5">Мы хотим построить сервис, который принесёт пользу всем участникам</h4>
            <ul class="lead">
                {% for client in clients %}
                    <li class="pt-3">
                        <strong class="text-warning">{{ client.0 }}</strong>
                        <p>{{ client.1 }}</p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>

    <div class="sb-secondary-bg">
        <section id="subscription" class="d-flex align-items-center py-5">
            <div class="container-md w-100" style="max-width: 600px !important;">
                <div class="text-center" >
                    <h1 class="mb-3">Наша рассылка</h1>
                    <p class="mb-3 text-start lead">
                        Подпишитесь, чтобы быть в курсе спецпредложений, акций, интересной информации о яхтинге и водномотрной жизни.
                        <br>
                        Выходит не чаще 2 раз в месяц.
                    </p>
                </div>
                <div class="d-flex justify-content-center mb-3">
                    <div class="py-3" style="width: 600px;">
                        <form method="post" action="https://cp.unisender.com/ru/subscribe?hash=6j7oxrqeykk49s8jgd158dwqyup8etisuqghrwchratexaizod6ky" class="needs-validation" novalidate>
                            
                            <input type="hidden" name="charset" value="UTF-8">
                            <input type="hidden" name="default_list_id" value="40">
                            <input type="hidden" name="overwrite" value="2">
                            <input type="hidden" name="is_v5" value="1">
                            
                            <div class="row row-cols-1 row-cols-lg-2 g-3 p-0">
                                <div class="col col-lg-8">
                                    <div class="form-floating">            
                                        <input id="email" type="email" name="email" autocomplete="email" placeholder="Эл. почта" required class="form-control" >
                                        <label for="email">Эл. почта</label>
                                        <div class="invalid-tooltip">Введите эл. почту</div>
                                    </div>
                                </div>
                                <div class="col col-lg-4">
                                    <button class="btn btn-lg btn-warning w-100 h-100" type="submit">Подписаться</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="bg-white text-black">
        <section id="feedback" class="container-md d-flex align-items-center position-relative mw-900 py-5">
            <div class="text-center w-100">
                <h1 class="mb-3">Есть вопросы?</h1>
                <p class="lead mb-5">Свяжитесь с нами любым удобным способом, мы с радостью Вас проконсультируем</p>

                <div class="row row-cols-1 row-cols-lg-4 g-3 text-center">
                    <div class="col">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-telephone me-1" viewBox="0 0 16 16">
                            <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                        </svg>
                        <u>{% settings_value "SUPPORT_PHONE" %}</u>
                    </div>

                    <div class="col">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-envelope me-1" viewBox="0 0 16 16">
                            <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
                        </svg>
                        <a href="mailto:{% settings_value 'SUPPORT_EMAIL' %}" class="text-black">{% settings_value "SUPPORT_EMAIL" %}</a>
                    </div>

                    <div class="col">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="none" viewBox="0 0 100 100" class="me-1">
                            <path fill="#0077FF" fill-rule="evenodd" clip-rule="evenodd" d="M50 100c27.614 0 50-22.386 50-50S77.614 0 50 0 0 22.386 0 50s22.386 50 50 50ZM25 34c.406 19.488 10.15 31.2 27.233 31.2h.968V54.05c6.278.625 11.024 5.216 12.93 11.15H75c-2.436-8.87-8.838-13.773-12.836-15.647C66.162 47.242 71.783 41.62 73.126 34h-8.058c-1.749 6.184-6.932 11.805-11.867 12.336V34h-8.057v21.611C40.147 54.362 33.838 48.304 33.556 34H25Z" />
                        </svg>
                        <a href="{% settings_value 'SUPPORT_EMAIL' %}" class="text-black" target="_blank">ВКонтакте</a>
                    </div>

                    <div class="col">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="none" viewBox="0 0 100 100" class="me-1">
                            <path fill="#54a9eb" fill-rule="evenodd" clip-rule="evenodd" d="M50 100c27.614 0 50-22.386 50-50S77.614 0 50 0 0 22.386 0 50s22.386 50 50 50Zm21.977-68.056c.386-4.38-4.24-2.576-4.24-2.576-3.415 1.414-6.937 2.85-10.497 4.302-11.04 4.503-22.444 9.155-32.159 13.734-5.268 1.932-2.184 3.864-2.184 3.864l8.351 2.577c3.855 1.16 5.91-.129 5.91-.129l17.988-12.238c6.424-4.38 4.882-.773 3.34.773l-13.49 12.882c-2.056 1.804-1.028 3.35-.129 4.123 2.55 2.249 8.82 6.364 11.557 8.16.712.467 1.185.778 1.292.858.642.515 4.111 2.834 6.424 2.319 2.313-.516 2.57-3.479 2.57-3.479l3.083-20.226c.462-3.511.993-6.886 1.417-9.582.4-2.546.705-4.485.767-5.362Z" />
                        </svg>
                        <a href="{% settings_value 'SUPPORT_EMAIL' %}" class="text-black" target="_blank">Telegram</a>
                    </div>
                </div>  
            </div>
        </section>
    </div>
{% endblock %}

app/templates/leaflet.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/leaflet-1.7.1.css' %}" />
<script type="text/javascript" src="{% static 'js/leaflet-1.7.1.min.js' %}"></script>

<script>
    var markerIconUrl = "{% static 'img/marker-icon.png' %}",
        markerShadowUrl = "{% static 'img/marker-shadow.png' %}";

    var markerIcon = L.icon({
        iconUrl: markerIconUrl,
        shadowUrl: markerShadowUrl,
    
        iconSize: [25, 41],
        iconAnchor: [12, 41],
        popupAnchor: [1, -34],
        shadowSize: [41, 41]
    });
</script>

app/templates/modal_map.html
{% load static %}

<script type="text/javascript" src="{% static 'js/modal_map.min.js' %}"></script>

<div id="modalMap" class="modal" tabindex="-1" role="dialog" style="display: none">
    <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <div class="modal-content shadow">
            <div class="modal-header">
                <h5 class="modal-title">Местоположение лодки</h5>
            </div>
            <div class="modal-body">
                <div class="mapContainer">
                    <div id="map" class="mb-3"></div>
                    <label class="addressLabel"></label>
                </div>
            </div>
            <div class="modal-footer d-block">             
                <div class="row g-0 m-0">
                    <div class="col col-lg-auto">                
                        <button type="button" class="btn btn-primary w-100" data-bs-dismiss="modal">Закрыть</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/nav.html
{% load static %}

<header class="navbar navbar-expand-lg navbar-dark {% if transparent %}bg-transparent{% else %}bg-nav{% endif %}">
    <nav class="container-lg flex-wrap flex-lg-nowrap">
        <button class="navbar-toggler collapsed no-focus" type="button" data-bs-toggle="offcanvas" data-bs-target="#menu" aria-controls="menu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon position-relative"></span>
        </button>
        
        <a class="navbar-brand me-auto p-2 pe-4" href="/">SHAREBOAT.RU</a>

        <div class="offcanvas offcanvas-start bg-nav" id="menu">
            <div class="offcanvas-header px-4">
                <h5 class="offcanvas-title text-white">SHAREBOAT.RU</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close" data-bs-target="#menu"></button>
            </div>
            <div class="offcanvas-body p-4 pt-0 p-lg-0">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'boat:search_boats' %}">Лодки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'booking:my_bookings' %}?status=active">Бронирования</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'boat:favs' %}">Избранное</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'portal:portal' %}">Портал</a>
                    </li>  
                </ul>
                
                {% if not user.is_authenticated %}
                    <ul class="navbar-nav ms-auto">          
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:login' %}?next={{ request.get_full_path|urlencode }}">Войти / Регистрация</a>
                        </li>              
                    </ul>
                {% else %}
                    <ul class="navbar-nav ms-auto">
                        {% if perms.user.view_support %}
                            <li class="nav-item py-1 col-12 col-lg-auto">
                                <hr class="d-lg-none text-white-50">
                            </li>  
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user:support' %}">
                                    Поддержка
                                </a>
                            </li>
                        {% endif %}
                        {% if perms.boat.view_my_boats %}  
                            <li class="nav-item py-1 col-12 col-lg-auto">
                                <hr class="d-lg-none text-white-50">
                            </li>   
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'booking:requests' %}?status={% if nav_counters.bookings_on_pending_count > 0 %}pending{% else %}active{% endif %}">
                                    Заявки
                                </a>
                            </li> 
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'boat:my_boats' %}">
                                    Мой флот
                                </a>
                            </li>
                            <li class="nav-item py-1 col-12 col-lg-auto">
                                <div class="vr d-none d-lg-flex h-100 mx-lg-2 text-white"></div>
                            </li> 
                        {% endif %}                    
                    </ul>
                {% endif %}
            </div>
        </div>
        
        {% if user.is_authenticated %}
            <a class="position-relative px-2" href="{% url 'chat:list' %}">
                <div class="position-relative">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="white" class="bi bi-envelope" viewBox="0 0 16 16">
                        <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
                    </svg>
                    {% if nav_counters.new_messages_count > 0 %}
                        <span class="position-absolute top-0 start-100 p-1 translate-middle-x bg-danger border border-light rounded-circle"></span>
                    {% endif %}
                </div>
            </a>
            <a id="navbarDropdownUserProfile" class="nav-link align-middle px-2" href="{% url 'user:update' %}">
                <img height="32" width="32" src="{% if user.avatar_sm %}{{ user.avatar_sm.url }}{% else %}{% static 'img/blank-profile-picture.png' %}{% endif %}" class="of-cover rounded-circle bg-light">                                            
            </a>
        {% endif %}
    </nav>
</header>

app/templates/nav_replacer.html
{% load static %}

<header class="navbar navbar-expand-md navbar-dark bg-nav sticky-top border-bottom">
    <nav class="container-md nav-replacer">
        <div class="hstack w-100">
            <div>  
                <a href="{{ back_link }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="54" height="38" fill="currentColor" class="bi bi-arrow-left-short back-arrow" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
                    </svg>
                </a>
            </div>
            {% block nav_replacer_title %}{% endblock %}
        </div>
    </nav>            
</header>

app/templates/nav_replacer_message.html
{% extends 'nav_replacer.html' %}
{% block nav_replacer_title %}
    <div class="navbar-brand ps-2 p-2 me-0 text-truncate"><span class="text-warning">{{ title|default:'Поддержка' }}</span></div>
{% endblock %}

app/templates/not_found.html
{% extends 'main.html' %}

{% block title %}Страница не найдена{% endblock  %}

{% block content %}
    <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">404</h1>
          <p class="lead text-muted">Страница не найдена</p>
        </div>
    </section>
{% endblock %}

app/templates/react.html
{% load static %}

<script type="text/javascript" src="{% static 'js/react17.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/react-dom17.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/axios.min.js' %}"></script>

app/templates/toast.html
<div id="toastContainer" class="toast-container position-fixed p-3 top-0 start-50 translate-middle-x">
    <div id="toast" class="toast bg-success shadow-sm position-relative" role="alert" aria-live="assertive" aria-atomic="true">
    </div>
</div>